# PostToolUse hook for Edit|Write. Formats only the file Claude just edited —
# never restores packages, never touches other files. Reads hook payload from
# stdin per Claude Code's hook contract (not from $args or terminal text).

$ErrorActionPreference = "Stop"

function Write-HookError {
    param([string]$Message)
    [Console]::Error.WriteLine($Message)
    exit 2
}

try {
    $rawInput = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($rawInput)) {
        exit 0
    }

    $hookInput = $rawInput | ConvertFrom-Json
    $filePath = $hookInput.tool_input.file_path

    if ([string]::IsNullOrWhiteSpace($filePath)) {
        exit 0
    }

    if (-not [string]::IsNullOrWhiteSpace($hookInput.cwd) -and (Test-Path -LiteralPath $hookInput.cwd -PathType Container)) {
        Set-Location -LiteralPath $hookInput.cwd
    }

    if ($filePath -notmatch '\.cs$') {
        exit 0
    }

    if (-not (Test-Path -LiteralPath $filePath -PathType Leaf)) {
        exit 0
    }

    $resolvedPath = (Resolve-Path -LiteralPath $filePath).ProviderPath
    $normalizedPath = $resolvedPath -replace '/', '\'

    # Build output and EF Core migrations (generated Designer/snapshot files
    # plus the hand-written Up()/Down() migration classes) are excluded from
    # formatting on purpose — see plan notes on why the whole folder is skipped.
    if ($normalizedPath -match '[\\/](obj|bin)[\\/]') {
        exit 0
    }
    if ($normalizedPath -match '[\\/]Migrations[\\/]') {
        exit 0
    }

    $headLines = Get-Content -LiteralPath $resolvedPath -TotalCount 5 -ErrorAction SilentlyContinue
    if ($headLines -and ($headLines -join "`n") -match '<auto-generated') {
        exit 0
    }

    $projectDir = Split-Path -Path $resolvedPath -Parent
    $csprojPath = $null
    for ($i = 0; $i -lt 15; $i++) {
        $candidates = Get-ChildItem -LiteralPath $projectDir -Filter '*.csproj' -File -ErrorAction SilentlyContinue
        if ($candidates) {
            $csprojPath = $candidates[0].FullName
            break
        }

        $parentDir = Split-Path -Path $projectDir -Parent
        if ([string]::IsNullOrEmpty($parentDir) -or $parentDir -eq $projectDir) {
            break
        }
        $projectDir = $parentDir
    }

    if (-not $csprojPath) {
        exit 0
    }

    # dotnet format resolves --include paths relative to the process's current
    # working directory, not the project/solution file's directory (verified
    # empirically — the docs' wording is misleading here).
    $baseDir = (Get-Location).ProviderPath
    $relativeFilePath = [System.IO.Path]::GetRelativePath($baseDir, $resolvedPath)

    $formatOutput = & dotnet format $csprojPath --include $relativeFilePath --no-restore --verbosity minimal 2>&1
    $exitCode = $LASTEXITCODE

    if ($exitCode -ne 0) {
        $message = "dotnet format failed for '$resolvedPath' (project '$csprojPath', exit code $exitCode):`n$($formatOutput -join "`n")"
        Write-HookError $message
    }

    exit 0
}
catch {
    Write-HookError "format-edited-file hook failed: $($_.Exception.Message)"
}
