# PostToolUse hook for Edit|Write|Bash|PowerShell. Formats only the .cs file(s)
# the tool call just touched — never restores packages, never touches other
# files. Reads hook payload from stdin per Claude Code's hook contract (not
# from $args or terminal text).

$ErrorActionPreference = "Stop"

function Write-HookError {
    param([string]$Message)
    [Console]::Error.WriteLine($Message)
    exit 2
}

function Get-CandidateCsFiles {
    param($HookInput)

    $toolName = $HookInput.tool_name
    if ($toolName -eq 'Edit' -or $toolName -eq 'Write') {
        $filePath = $HookInput.tool_input.file_path
        if ([string]::IsNullOrWhiteSpace($filePath)) {
            return @()
        }
        return @($filePath)
    }

    if ($toolName -eq 'Bash' -or $toolName -eq 'PowerShell') {
        $command = $HookInput.tool_input.command
        if ([string]::IsNullOrWhiteSpace($command)) {
            return @()
        }

        # Best-effort: catches the common redirection/cmdlet shapes used to write
        # a file from a shell command. Not exhaustive (arbitrary scripting can
        # still evade this), but covers the realistic cases.
        $patterns = @(
            '>>?\s*[''"]?([^\s''"<>|;]+\.cs)[''"]?',
            '(?:Out-File|Set-Content|Add-Content)\s+(?:-Path\s+|-FilePath\s+)?[''"]?([^\s''"|;]+\.cs)[''"]?'
        )
        $paths = @()
        foreach ($pattern in $patterns) {
            $paths += [regex]::Matches($command, $pattern) | ForEach-Object { $_.Groups[1].Value }
        }
        return @($paths | Select-Object -Unique)
    }

    return @()
}

function Format-CSharpFile {
    param([string]$FilePath)

    if ($FilePath -notmatch '\.cs$') {
        return
    }

    if (-not (Test-Path -LiteralPath $FilePath -PathType Leaf)) {
        return
    }

    $resolvedPath = (Resolve-Path -LiteralPath $FilePath).ProviderPath
    $normalizedPath = $resolvedPath -replace '/', '\'

    if ($normalizedPath -match '[\\/](obj|bin)[\\/]') {
        return
    }
    if ($normalizedPath -match '[\\/]Migrations[\\/]') {
        return
    }

    $headLines = Get-Content -LiteralPath $resolvedPath -TotalCount 5 -ErrorAction SilentlyContinue
    if ($headLines -and ($headLines -join "`n") -match '<auto-generated') {
        return
    }

    $projectDir = Split-Path -Path $resolvedPath -Parent
    $csprojPath = $null
    while ($true) {
        $candidates = Get-ChildItem -LiteralPath $projectDir -Filter '*.csproj' -File -ErrorAction SilentlyContinue
        if ($candidates) {
            # More than one .csproj in the same directory is ambiguous — there's
            # no reliable way to tell which one owns the edited file, so skip
            # rather than guess.
            if ($candidates.Count -eq 1) {
                $csprojPath = $candidates[0].FullName
            }
            break
        }

        $parentDir = Split-Path -Path $projectDir -Parent
        if ([string]::IsNullOrEmpty($parentDir) -or $parentDir -eq $projectDir) {
            break
        }
        $projectDir = $parentDir
    }

    if (-not $csprojPath) {
        return
    }

    # dotnet format resolves --include paths relative to the process's current
    # working directory, not the project/solution file's directory (verified
    # empirically — the docs' wording is misleading here).
    $baseDir = (Get-Location).ProviderPath
    $relativeFilePath = [System.IO.Path]::GetRelativePath($baseDir, $resolvedPath)

    # PowerShell 7.3+ defaults $PSNativeCommandUseErrorActionPreference to $true,
    # which combined with $ErrorActionPreference = "Stop" would turn dotnet
    # format's non-zero exit into an immediate terminating exception — skipping
    # the diagnostic message below and losing $formatOutput. Suspend it locally
    # so a format failure is reported with the real formatter output instead.
    $previousNativePreference = $PSNativeCommandUseErrorActionPreference
    $PSNativeCommandUseErrorActionPreference = $false
    try {
        $formatOutput = & dotnet format $csprojPath --include $relativeFilePath --no-restore --verbosity minimal 2>&1
        $exitCode = $LASTEXITCODE
    }
    finally {
        $PSNativeCommandUseErrorActionPreference = $previousNativePreference
    }

    if ($exitCode -ne 0) {
        return "dotnet format failed for '$resolvedPath' (project '$csprojPath', exit code $exitCode):`n$($formatOutput -join "`n")"
    }

    return $null
}

try {
    $rawInput = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($rawInput)) {
        exit 0
    }

    $hookInput = $rawInput | ConvertFrom-Json

    if (-not [string]::IsNullOrWhiteSpace($hookInput.cwd) -and (Test-Path -LiteralPath $hookInput.cwd -PathType Container)) {
        Set-Location -LiteralPath $hookInput.cwd
    }

    $candidateFiles = Get-CandidateCsFiles -HookInput $hookInput
    if (-not $candidateFiles -or $candidateFiles.Count -eq 0) {
        exit 0
    }

    $errors = @()
    foreach ($candidateFile in $candidateFiles) {
        $result = Format-CSharpFile -FilePath $candidateFile
        if ($result) {
            $errors += $result
        }
    }

    if ($errors.Count -gt 0) {
        Write-HookError ($errors -join "`n`n")
    }

    exit 0
}
catch {
    Write-HookError "format-edited-file hook failed: $($_.Exception.Message)"
}
