organization:
    id: 20a0c0a4-82ed-4a8a-8743-94223a82c1b3
    name: nix-test
project:
    id: 43d7e768-bd49-4c81-a0d3-6a6cfdccdcfe
    slug: circleci/52ggUskczcSwSiqh2q6Lae/9NuDB6MmuVpodHzUd4ESa9
    name: TaskFlow
